# Generated by Django 5.1.4 on 2025-01-04 12:45

import walletapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[walletapi.models.validate_balance]),
        ),
    ]
